### PR TITLE
Add a failOnError method

### LINKED ISSUE #13: Add a fail reporter
We should add a fail reporter that can be used to fail the build if there are linting errors.

### PR DESCRIPTION
**Pull request by jwilsson**
I'd like some feedback on this. Good, bad, something else? Let me know!

Sample usage
```js
var gulp = require('gulp');
var lesshint = require('gulp-lesshint');

gulp.task('lint', function() {
    return gulp.src('./src/*.less')
        .pipe(lesshint())
        .pipe(lesshint.reporter())
        .pipe(lesshint.failOnError());
});
```

Closes #13.

### CODE REVIEW

**Comment by justtal** [comment]
Can someone merge it? We are having the same requirements. Thanks!

**Comment by vlio20** [comment]
+1

**Comment by santiph** [comment]
+1

**Comment by jwilsson** [comment]
Totally forgot about this one but now it's released in `2.1.0`!

**Comment by DamienCassou** [comment]
Works fine, thanks.

**Pull request merged**
