### PR TITLE
Add "end" event emitter to `failOnErrors()` so that it will work with merged streams

### PR DESCRIPTION
**Pull request by jpencola**
First, thanks for the open-source work you've done 👍 

I'd like to propose adding an event emitter when the combination of using `failOnError` and zero errors are reported occur in a pipeline. 

Currently, if you use a module like [merge-stream](https://www.npmjs.com/package/merge-stream), and create a gulp task like this (where "lessHintTask" internally relies on gulp-lesshint with a `.pipe(lesshint.failOnError())`):

```
gulp.task('taskName', () => {
    return mergeStream(
      'subtaskOne',
      'subtaskTwo,
      'lessHintTask')
  })
```

If zero errors are reported, the stream never ends and merge-stream never completes which leaves the task open.

Thanks for your consideration

### CODE REVIEW

**Comment by jwilsson** [comment]
Hi,
Thank you!

A quick question, would `return cb();` work instead?

**Comment by jpencola** [comment]
Indeed it does! Would you like me to update the PR with that instead?

**Comment by jwilsson** [comment]
That would be great, a bit shorter too 😄

**Comment by jwilsson** [comment]
Thanks for contributing! 🎉 

This will be included in `3.0.0` which will hopefully be out in the next few days.

**Comment by marcrd** [comment]
@jwilsson any update on when this would be versioned? Running into this bug the PR fixes on a build

**Comment by jwilsson** [comment]
@marcrd I'm preparing the release right now!

**Comment by jwilsson** [comment]
@jpencola @marcrd `3.0.0` has just been released! 🎉

**Pull request merged**
